Add devise
asnganje/Blog-App pull request #9
Opened 2023-02-01 21:55 UTC by asnganje

## Dear reviewer

In this project, we have accomplished the following requirements

- Remove current_user method in ApplicationController, devise will provided us with one.

- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset password.
- [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and our styling.

2023-02-01 22:26 UTC, Munsa1 requested changes
Hi @asnganje, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed I will leave a comment here
- [ ] Kindly add the right key features to your `key features` section in your readme file
![image](https://user-images.githubusercontent.com/81932478/216177766-e6c73672-f074-40e8-8599-c2e3250231cf.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 22:26 UTC, Munsa1 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] The application should ask for confirmation of email as this is a reqiurement. `:confirmable`  should be enabled in the user model. Kindly do so

2023-02-01 22:26 UTC, Munsa1 commented on app/views/devise/sessions/new.html.erb
> +  </div>
- [ ] The views in devise for the registration and login should be modified to match the wireframes and their styling. Kindly do so.

Your design
![image](https://user-images.githubusercontent.com/81932478/216176898-7ce69b96-893f-42b5-8a65-9ce091d5fa9e.png)

Given Wireframe
![image](https://user-images.githubusercontent.com/81932478/216177020-5b334387-58d9-4ba2-ade7-8b51cf82a61b.png)

2023-02-02 00:17 UTC, Munsa1 requested changes
Hi @asnganje, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 00:17 UTC, Munsa1 commented on app/views/devise/sessions/new.html.erb
> +<% end %>
- [ ] As requested earlier, kindly follow the given design for the login and sign up page as this is required

Your design
![image](https://user-images.githubusercontent.com/81932478/216198759-b7003343-af74-4959-8da4-3c4be04ae07e.png)

Given wireframe
![image](https://user-images.githubusercontent.com/81932478/216198915-a9061198-bd69-4752-b41c-77c21a3501f7.png)

2023-02-02 01:24 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @asnganje, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Clean code.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-02 08:41 UTC, merged